(in-package #:wao)

(defun expand (wat-code)
	(let ((operator (car wat-code)))
		(cond ((string= "FUNC" operator)
		      	   (expand-func   (cdr wat-code)))
		      ((string= "EXPORT" operator)
			       (expand-export (cdr wat-code)))
		      ((string= "MEMORY" operator)
			       (expand-memory (cdr wat-code)))
		      ((string= "TABLE" operator)
			       (expand-table (cdr wat-code)))
		      (t (error-notification "undefined base")))
	)
)
